### ISSUE TITLE
Different load metrics, depending on the OS version (debian in my case)

### ISSUE THREAD

**Issue by zanoubia** [sensu-plugins/sensu-plugins-load-checks#11]
Hello,

The load metrics are different depending on the uptime command output.
Examples :

vm 1 (0<metrics<1)
# uptime

 18:49:03 up 116 days, 21 min,  2 users,  load average: 0.86, 1.15, 1.04
# /opt/sensu/embedded/bin/metrics-load.rb -p

maamsprd01.amabis.ma.load_avg.one 0.22 1475858943
maamsprd01.amabis.ma.load_avg.five 0.29 1475858943
maamsprd01.amabis.ma.load_avg.fifteen 0.26 1475858943

vm2 (0<metrics<100   %)
# uptime

  17:48:54 up 105 days,  6:00,  0 users,  load average: 0,82, 0,96, 0,77
# /opt/sensu/embedded/bin/metrics-load.rb -p

masmtprd01.amabis.ma.load_avg.one 41.0 1475858935
masmtprd01.amabis.ma.load_avg.five 48.0 1475858935
masmtprd01.amabis.ma.load_avg.fifteen 38.5 1475858935

Maybe the line https://github.com/sensu-plugins/sensu-plugins-load-checks/blob/master/bin/metrics-load.rb#L61 must be update to include floats with '.' ;

**Comment by majormoses** [comment]
@zanoubia yes that is brittle and not only breaks there but with different locales, we should look for another solution.

**Comment by majormoses** [comment]
exact same root cause: https://github.com/sensu-plugins/sensu-plugins-load-checks/issues/5

**Comment by majormoses** [comment]
@zanoubia can you verify if this solves your issue?

**Comment by majormoses** [comment]
@zanoubia can you verify this fixes your issue? https://github.com/sensu-plugins/sensu-plugins-load-checks/pull/15

**Comment by majormoses** [comment]
should be fixed via: https://rubygems.org/gems/sensu-plugins-load-checks/versions/3.0.0

**Comment by rholloway** [comment]
@majormoses Can you help me understand why --per-core was removed?

You are right in that load metrics are not useful without knowing number of cores. I thought that was precisely the benefit of using --per-core. It allows users to programmatically normalize load metrics across different sized hosts for alerting purposes (ie a load of 4 on a single core box may not be great and we may want an alert, whereas a load of 4 on a 16 core box is nothing to worry about at all).

**Comment by majormoses** [comment]
@rholloway the option was removed and the functionality was changed to only return per core values. If there is an option that there is no value in allowing the user to change then you might as well not let them. 

Originally it was not written as such and so I have over time changed the behavior to defaulting to true on per core to help people transition but then decided in a later release we should just remove it as it simplified the code and is the right thing to do.

**Comment by rholloway** [comment]
@majormoses I'm not sure I follow. So does that mean that in 3.x the default without parameter is the same as using --per-core on 2.x? We use --per-core on 2.x today. If the functionality in 3.x was changed to only return per core values, it sounds like 3.x won't cause any issues for us, we just need to remove --per-core parameter since it's the default now and no longer a toggle.

**Comment by majormoses** [comment]
Yup, just remove the option if you were using per core. For anyone not using it previously they should determine a new threshold that makes sense.
