### ISSUE TITLE
load metrics doesn't work with  fr_FR.UTF-8 locale (and probably others...)

### ISSUE THREAD

**Issue by mguthmuller** [sensu-plugins/sensu-plugins-load-checks#5]
Hi,

Load metrics doesn't work with fr_FR.UTF-8 (and probably) locale because of your parsing of uptime result: 

`result =`uptime`.delete(',').split(' ')`

',' is used instead of '.' in order to separate decimals in the numbers. Since you do a delete on this separator, a load initially equal to 1.42 becomes equal to 142

I think you should add a check of locale settings before parsing the uptime result.

**Comment by majormoses** [comment]
@mguthmuller can you verify https://github.com/sensu-plugins/sensu-plugins-load-checks/pull/15 solves your issue?

**Comment by majormoses** [comment]
should be fixed via: https://rubygems.org/gems/sensu-plugins-load-checks/versions/3.0.0
